In [2]:
import pandas as pd
FrameWork_Data = { 
    "Name":["Vahini","Joyce","Arun","Varshini","Neha","Sabastin"],
    "Language":[66,78,93,83,53,23],
    "English":[88,57,53,34,87,99],
    "Mathematics":[65,75,87,49,33,82],
    "Computer Science":[87,76,98,56,63,84],
    "Physics":[55,47,85,94,75,58],
    "Chemistry":[48,80,95,42,75,96],
}
Data_Frame = pd.DataFrame(FrameWork_Data)
Data_Frame["Total" ]= Data_Frame["Language"]+Data_Frame["English"]+Data_Frame["Mathematics"]+Data_Frame["Computer Science"]+Data_Frame["Physics"]+Data_Frame["Chemistry"]
Data_Frame["Average"] = Data_Frame["Total"]/6
print(Data_Frame)

       Name  Language  English  Mathematics  Computer Science  Physics  \
0    Vahini        66       88           65                87       55
1     Joyce        78       57           75                76       47
2      Arun        93       53           87                98       85
3  Varshini        83       34           49                56       94
4      Neha        53       87           33                63       75
5  Sabastin        23       99           82                84       58

   Chemistry  Total    Average
0         48    409  68.166667
1         80    413  68.833333
2         95    511  85.166667
3         42    358  59.666667
4         75    386  64.333333
5         96    442  73.666667

In [3]:
df = pd.read_csv("dataset_performance.csv")

In [4]:
print(df) #Reads data from a CSV file and loads it into a pandas DataFrame.

       student_id  age  gender             major  study_hours_per_day  \
0          100000   26    Male  Computer Science             7.645367
1          100001   28    Male              Arts             5.700000
2          100002   17    Male              Arts             2.400000
3          100003   27   Other        Psychology             3.400000
4          100004   25  Female          Business             4.700000
...           ...  ...     ...               ...                  ...
79995      179995   16    Male       Engineering             3.700000
79996      179996   16  Female          Business             1.200000
79997      179997   26  Female              Arts             4.100000
79998      179998   23   Other           Biology             3.800000
79999      179999   25   Other       Engineering             3.000000

       social_media_hours  netflix_hours part_time_job  attendance_percentage  \
0                     3.0            0.1           Yes                   70.3
1                     0.5            0.4            No                   88.4
2                     4.2            0.7            No                   82.1
3                     4.6            2.3           Yes                   79.3
4                     0.8            2.7           Yes                   62.9
...                   ...            ...           ...                    ...
79995                 2.1            1.0           Yes                   80.8
79996                 0.4            2.9            No                   99.5
79997                 1.6            1.6           Yes                   46.1
79998                 0.6            3.5           Yes                   58.7
79999                 4.5            3.4           Yes                   97.7

       sleep_hours  ... screen_time  study_environment access_to_tutoring  \
0              6.2  ...        10.9  Co-Learning Group                Yes
1              7.2  ...         8.3  Co-Learning Group                Yes
2              9.2  ...         8.0            Library                Yes
3              4.2  ...        11.7  Co-Learning Group                Yes
4              6.5  ...         9.4         Quiet Room                Yes
...            ...  ...         ...                ...                ...
79995          6.1  ...         8.3            Library                 No
79996          4.1  ...         4.7  Co-Learning Group                 No
79997          8.3  ...         7.5               Dorm                 No
79998          5.8  ...         9.3         Quiet Room                Yes
79999          5.3  ...        12.2  Co-Learning Group                Yes

      family_income_range  parental_support_level motivation_level  \
0                    High                       9                7
1                     Low                       7                2
2                    High                       3                9
3                     Low                       5                3
4                  Medium                       9                1
...                   ...                     ...              ...
79995                 Low                       1                4
79996                 Low                       3                2
79997              Medium                       7                1
79998                 Low                       2                8
79999              Medium                       1                8

       exam_anxiety_score  learning_style  time_management_score exam_score
0                       8         Reading                    3.0        100
1                      10         Reading                    6.0         99
2                       6     Kinesthetic                    7.6         98
3                      10         Reading                    3.2        100
4                      10         Reading                    7.1         98
...                   ...             ...                    ...        ...
79995                  10        Auditory                    5.3         88
79996                  10     Kinesthetic                    6.8         52
79997                  10          Visual                    1.3         89
79998                   7     Kinesthetic                    3.7         96
79999                   7         Reading                    6.7        100

[80000 rows x 31 columns]

In [5]:
df.head() #Shows the first 5 rows of the DataFrame by default.

,student_id,age,gender,major,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,...,screen_time,study_environment,access_to_tutoring,family_income_range,parental_support_level,motivation_level,exam_anxiety_score,learning_style,time_management_score,exam_score
0,100000,26,Male,Computer Science,7.645367,3.0,0.1,Yes,70.3,6.2,...,10.9,Co-Learning Group,Yes,High,9,7,8,Reading,3.0,100
1,100001,28,Male,Arts,5.700000,0.5,0.4,No,88.4,7.2,...,8.3,Co-Learning Group,Yes,Low,7,2,10,Reading,6.0,99
2,100002,17,Male,Arts,2.400000,4.2,0.7,No,82.1,9.2,...,8.0,Library,Yes,High,3,9,6,Kinesthetic,7.6,98
3,100003,27,Other,Psychology,3.400000,4.6,2.3,Yes,79.3,4.2,...,11.7,Co-Learning Group,Yes,Low,5,3,10,Reading,3.2,100
4,100004,25,Female,Business,4.700000,0.8,2.7,Yes,62.9,6.5,...,9.4,Quiet Room,Yes,Medium,9,1,10,Reading,7.1,98

In [6]:
df.tail() #Shows the last 5 rows of the DataFrame by default.

,student_id,age,gender,major,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,...,screen_time,study_environment,access_to_tutoring,family_income_range,parental_support_level,motivation_level,exam_anxiety_score,learning_style,time_management_score,exam_score
79995,179995,16,Male,Engineering,3.7,2.1,1.0,Yes,80.8,6.1,...,8.3,Library,No,Low,1,4,10,Auditory,5.3,88
79996,179996,16,Female,Business,1.2,0.4,2.9,No,99.5,4.1,...,4.7,Co-Learning Group,No,Low,3,2,10,Kinesthetic,6.8,52
79997,179997,26,Female,Arts,4.1,1.6,1.6,Yes,46.1,8.3,...,7.5,Dorm,No,Medium,7,1,10,Visual,1.3,89
79998,179998,23,Other,Biology,3.8,0.6,3.5,Yes,58.7,5.8,...,9.3,Quiet Room,Yes,Low,2,8,7,Kinesthetic,3.7,96
79999,179999,25,Other,Engineering,3.0,4.5,3.4,Yes,97.7,5.3,...,12.2,Co-Learning Group,Yes,Medium,1,8,7,Reading,6.7,100

In [7]:
df.info() #Displays a summary of the DataFrame[no.of rows and columns,Column names and data types,shows Non-null counts and Memory usage]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 31 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   student_id                     80000 non-null  int64
 1   age                            80000 non-null  int64
 2   gender                         80000 non-null  object
 3   major                          80000 non-null  object
 4   study_hours_per_day            80000 non-null  float64
 5   social_media_hours             80000 non-null  float64
 6   netflix_hours                  80000 non-null  float64
 7   part_time_job                  80000 non-null  object
 8   attendance_percentage          80000 non-null  float64
 9   sleep_hours                    80000 non-null  float64
 10  diet_quality                   80000 non-null  object
 11  exercise_frequency             80000 non-null  int64
 12  parental_education_level       80000 non-null  object
 13  internet_quality               80000 non-null  object
 14  mental_health_rating           80000 non-null  float64
 15  extracurricular_participation  80000 non-null  object
 16  previous_gpa                   80000 non-null  float64
 17  semester                       80000 non-null  int64
 18  stress_level                   80000 non-null  float64
 19  dropout_risk                   80000 non-null  object
 20  social_activity                80000 non-null  int64
 21  screen_time                    80000 non-null  float64
 22  study_environment              80000 non-null  object
 23  access_to_tutoring             80000 non-null  object
 24  family_income_range            80000 non-null  object
 25  parental_support_level         80000 non-null  int64
 26  motivation_level               80000 non-null  int64
 27  exam_anxiety_score             80000 non-null  int64
 28  learning_style                 80000 non-null  object
 29  time_management_score          80000 non-null  float64
 30  exam_score                     80000 non-null  int64
dtypes: float64(10), int64(9), object(12)
memory usage: 18.9+ MB

In [8]:
df.describe() #Gives statistical summary of columns [Count, mean, std (standard deviation), min, max, Percentage]

,student_id,age,study_hours_per_day,social_media_hours,netflix_hours,attendance_percentage,sleep_hours,exercise_frequency,mental_health_rating,previous_gpa,semester,stress_level,social_activity,screen_time,parental_support_level,motivation_level,exam_anxiety_score,time_management_score,exam_score
count,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000
mean,139999.500000,22.004288,4.174388,2.501366,1.997754,69.967884,7.017417,3.516587,6.804107,3.602448,4.497338,5.012478,2.500225,9.673029,5.479438,5.488525,8.508475,5.499132,89.141350
std,23094.155105,3.745570,2.004135,1.445441,1.155992,17.333015,1.467377,2.291575,1.921579,0.462876,2.295312,1.953174,1.704292,2.780869,2.873327,2.867782,1.796411,2.603534,11.591497
min,100000.000000,16.000000,0.000000,0.000000,0.000000,40.000000,4.000000,0.000000,1.000000,1.640000,1.000000,1.000000,0.000000,0.300000,1.000000,1.000000,5.000000,1.000000,36.000000
25%,119999.750000,19.000000,2.800000,1.200000,1.000000,55.000000,6.000000,2.000000,5.500000,3.270000,2.000000,3.600000,1.000000,7.800000,3.000000,3.000000,7.000000,3.200000,82.000000
50%,139999.500000,22.000000,4.125624,2.500000,2.000000,69.900000,7.000000,4.000000,6.900000,3.790000,5.000000,5.000000,2.000000,9.700000,5.000000,5.000000,10.000000,5.500000,93.000000
75%,159999.250000,25.000000,5.500000,3.800000,3.000000,84.900000,8.000000,6.000000,8.200000,4.000000,7.000000,6.400000,4.000000,11.600000,8.000000,8.000000,10.000000,7.800000,100.000000
max,179999.000000,28.000000,12.000000,5.000000,4.000000,100.000000,12.000000,7.000000,10.000000,4.000000,8.000000,10.000000,5.000000,21.000000,10.000000,10.000000,10.000000,10.000000,100.000000

In [9]:
df.shape #Returns a tuple (rows, columns) showing the size of the DataFrame.

(80000, 31)

In [10]:
df.isnull() #Returns a DataFrame of True/False values indicating where values are missing (NaN)

,student_id,age,gender,major,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,...,screen_time,study_environment,access_to_tutoring,family_income_range,parental_support_level,motivation_level,exam_anxiety_score,learning_style,time_management_score,exam_score
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
79996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
79997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
79998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
79999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [11]:
df.isnull().sum #Gives the count of missing values per column.

<bound method DataFrame.sum of        student_id    age  gender  major  study_hours_per_day  \
0           False  False   False  False                False
1           False  False   False  False                False
2           False  False   False  False                False
3           False  False   False  False                False
4           False  False   False  False                False
...           ...    ...     ...    ...                  ...
79995       False  False   False  False                False
79996       False  False   False  False                False
79997       False  False   False  False                False
79998       False  False   False  False                False
79999       False  False   False  False                False

       social_media_hours  netflix_hours  part_time_job  \
0                   False          False          False
1                   False          False          False
2                   False          False          False
3                   False          False          False
4                   False          False          False
...                   ...            ...            ...
79995               False          False          False
79996               False          False          False
79997               False          False          False
79998               False          False          False
79999               False          False          False

       attendance_percentage  sleep_hours  ...  screen_time  \
0                      False        False  ...        False
1                      False        False  ...        False
2                      False        False  ...        False
3                      False        False  ...        False
4                      False        False  ...        False
...                      ...          ...  ...          ...
79995                  False        False  ...        False
79996                  False        False  ...        False
79997                  False        False  ...        False
79998                  False        False  ...        False
79999                  False        False  ...        False

       study_environment  access_to_tutoring  family_income_range  \
0                  False               False                False
1                  False               False                False
2                  False               False                False
3                  False               False                False
4                  False               False                False
...                  ...                 ...                  ...
79995              False               False                False
79996              False               False                False
79997              False               False                False
79998              False               False                False
79999              False               False                False

       parental_support_level  motivation_level  exam_anxiety_score  \
0                       False             False               False
1                       False             False               False
2                       False             False               False
3                       False             False               False
4                       False             False               False
...                       ...               ...                 ...
79995                   False             False               False
79996                   False             False               False
79997                   False             False               False
79998                   False             False               False
79999                   False             False               False

       learning_style  time_management_score  exam_score
0               False                  False       False
1               False                  False       False
2               False                  False       False
3               False                  False       False
4               False                  False       False
...               ...                    ...         ...
79995           False                  False       False
79996           False                  False       False
79997           False                  False       False
79998           False                  False       False
79999           False                  False       False

[80000 rows x 31 columns]>

In [12]:
df.duplicated() #Returns a Boolean value indicating which rows are duplicates of earlier rows.

0        False
1        False
2        False
3        False
4        False
         ...
79995    False
79996    False
79997    False
79998    False
79999    False
Length: 80000, dtype: bool

In [13]:
df.duplicated().sum #Counts how many duplicate rows are in the DataFrame.

<bound method Series.sum of 0        False
1        False
2        False
3        False
4        False
         ...
79995    False
79996    False
79997    False
79998    False
79999    False
Length: 80000, dtype: bool>

In [14]:
df = pd.read_csv("dataset_performance.csv")
print(df)

       student_id  age  gender             major  study_hours_per_day  \
0          100000   26    Male  Computer Science             7.645367
1          100001   28    Male              Arts             5.700000
2          100002   17    Male              Arts             2.400000
3          100003   27   Other        Psychology             3.400000
4          100004   25  Female          Business             4.700000
...           ...  ...     ...               ...                  ...
79995      179995   16    Male       Engineering             3.700000
79996      179996   16  Female          Business             1.200000
79997      179997   26  Female              Arts             4.100000
79998      179998   23   Other           Biology             3.800000
79999      179999   25   Other       Engineering             3.000000

       social_media_hours  netflix_hours part_time_job  attendance_percentage  \
0                     3.0            0.1           Yes                   70.3
1                     0.5            0.4            No                   88.4
2                     4.2            0.7            No                   82.1
3                     4.6            2.3           Yes                   79.3
4                     0.8            2.7           Yes                   62.9
...                   ...            ...           ...                    ...
79995                 2.1            1.0           Yes                   80.8
79996                 0.4            2.9            No                   99.5
79997                 1.6            1.6           Yes                   46.1
79998                 0.6            3.5           Yes                   58.7
79999                 4.5            3.4           Yes                   97.7

       sleep_hours  ... screen_time  study_environment access_to_tutoring  \
0              6.2  ...        10.9  Co-Learning Group                Yes
1              7.2  ...         8.3  Co-Learning Group                Yes
2              9.2  ...         8.0            Library                Yes
3              4.2  ...        11.7  Co-Learning Group                Yes
4              6.5  ...         9.4         Quiet Room                Yes
...            ...  ...         ...                ...                ...
79995          6.1  ...         8.3            Library                 No
79996          4.1  ...         4.7  Co-Learning Group                 No
79997          8.3  ...         7.5               Dorm                 No
79998          5.8  ...         9.3         Quiet Room                Yes
79999          5.3  ...        12.2  Co-Learning Group                Yes

      family_income_range  parental_support_level motivation_level  \
0                    High                       9                7
1                     Low                       7                2
2                    High                       3                9
3                     Low                       5                3
4                  Medium                       9                1
...                   ...                     ...              ...
79995                 Low                       1                4
79996                 Low                       3                2
79997              Medium                       7                1
79998                 Low                       2                8
79999              Medium                       1                8

       exam_anxiety_score  learning_style  time_management_score exam_score
0                       8         Reading                    3.0        100
1                      10         Reading                    6.0         99
2                       6     Kinesthetic                    7.6         98
3                      10         Reading                    3.2        100
4                      10         Reading                    7.1         98
...                   ...             ...                    ...        ...
79995                  10        Auditory                    5.3         88
79996                  10     Kinesthetic                    6.8         52
79997                  10          Visual                    1.3         89
79998                   7     Kinesthetic                    3.7         96
79999                   7         Reading                    6.7        100

[80000 rows x 31 columns]

In [15]:
df=df.drop(columns=['netflix_hours'])
print(df)

       student_id  age  gender             major  study_hours_per_day  \
0          100000   26    Male  Computer Science             7.645367
1          100001   28    Male              Arts             5.700000
2          100002   17    Male              Arts             2.400000
3          100003   27   Other        Psychology             3.400000
4          100004   25  Female          Business             4.700000
...           ...  ...     ...               ...                  ...
79995      179995   16    Male       Engineering             3.700000
79996      179996   16  Female          Business             1.200000
79997      179997   26  Female              Arts             4.100000
79998      179998   23   Other           Biology             3.800000
79999      179999   25   Other       Engineering             3.000000

       social_media_hours part_time_job  attendance_percentage  sleep_hours  \
0                     3.0           Yes                   70.3          6.2
1                     0.5            No                   88.4          7.2
2                     4.2            No                   82.1          9.2
3                     4.6           Yes                   79.3          4.2
4                     0.8           Yes                   62.9          6.5
...                   ...           ...                    ...          ...
79995                 2.1           Yes                   80.8          6.1
79996                 0.4            No                   99.5          4.1
79997                 1.6           Yes                   46.1          8.3
79998                 0.6           Yes                   58.7          5.8
79999                 4.5           Yes                   97.7          5.3

      diet_quality  ...  screen_time  study_environment access_to_tutoring  \
0             Poor  ...         10.9  Co-Learning Group                Yes
1             Good  ...          8.3  Co-Learning Group                Yes
2             Good  ...          8.0            Library                Yes
3             Fair  ...         11.7  Co-Learning Group                Yes
4             Good  ...          9.4         Quiet Room                Yes
...            ...  ...          ...                ...                ...
79995         Fair  ...          8.3            Library                 No
79996         Good  ...          4.7  Co-Learning Group                 No
79997         Good  ...          7.5               Dorm                 No
79998         Good  ...          9.3         Quiet Room                Yes
79999         Fair  ...         12.2  Co-Learning Group                Yes

       family_income_range parental_support_level  motivation_level  \
0                     High                      9                 7
1                      Low                      7                 2
2                     High                      3                 9
3                      Low                      5                 3
4                   Medium                      9                 1
...                    ...                    ...               ...
79995                  Low                      1                 4
79996                  Low                      3                 2
79997               Medium                      7                 1
79998                  Low                      2                 8
79999               Medium                      1                 8

       exam_anxiety_score  learning_style time_management_score  exam_score
0                       8         Reading                   3.0         100
1                      10         Reading                   6.0          99
2                       6     Kinesthetic                   7.6          98
3                      10         Reading                   3.2         100
4                      10         Reading                   7.1          98
...                   ...             ...                   ...         ...
79995                  10        Auditory                   5.3          88
79996                  10     Kinesthetic                   6.8          52
79997                  10          Visual                   1.3          89
79998                   7     Kinesthetic                   3.7          96
79999                   7         Reading                   6.7         100

[80000 rows x 30 columns]

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 30 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   student_id                     80000 non-null  int64
 1   age                            80000 non-null  int64
 2   gender                         80000 non-null  object
 3   major                          80000 non-null  object
 4   study_hours_per_day            80000 non-null  float64
 5   social_media_hours             80000 non-null  float64
 6   part_time_job                  80000 non-null  object
 7   attendance_percentage          80000 non-null  float64
 8   sleep_hours                    80000 non-null  float64
 9   diet_quality                   80000 non-null  object
 10  exercise_frequency             80000 non-null  int64
 11  parental_education_level       80000 non-null  object
 12  internet_quality               80000 non-null  object
 13  mental_health_rating           80000 non-null  float64
 14  extracurricular_participation  80000 non-null  object
 15  previous_gpa                   80000 non-null  float64
 16  semester                       80000 non-null  int64
 17  stress_level                   80000 non-null  float64
 18  dropout_risk                   80000 non-null  object
 19  social_activity                80000 non-null  int64
 20  screen_time                    80000 non-null  float64
 21  study_environment              80000 non-null  object
 22  access_to_tutoring             80000 non-null  object
 23  family_income_range            80000 non-null  object
 24  parental_support_level         80000 non-null  int64
 25  motivation_level               80000 non-null  int64
 26  exam_anxiety_score             80000 non-null  int64
 27  learning_style                 80000 non-null  object
 28  time_management_score          80000 non-null  float64
 29  exam_score                     80000 non-null  int64
dtypes: float64(9), int64(9), object(12)
memory usage: 18.3+ MB

In [17]:
updated_age = df[df['age']>=18]
print(updated_age)

       student_id  age  gender             major  study_hours_per_day  \
0          100000   26    Male  Computer Science             7.645367
1          100001   28    Male              Arts             5.700000
3          100003   27   Other        Psychology             3.400000
4          100004   25  Female          Business             4.700000
6          100006   19    Male        Psychology             4.100000
...           ...  ...     ...               ...                  ...
79993      179993   28    Male              Arts             1.300000
79994      179994   24   Other          Business             3.800000
79997      179997   26  Female              Arts             4.100000
79998      179998   23   Other           Biology             3.800000
79999      179999   25   Other       Engineering             3.000000

       social_media_hours part_time_job  attendance_percentage  sleep_hours  \
0                     3.0           Yes                   70.3          6.2
1                     0.5            No                   88.4          7.2
3                     4.6           Yes                   79.3          4.2
4                     0.8           Yes                   62.9          6.5
6                     2.4           Yes                   97.9          8.5
...                   ...           ...                    ...          ...
79993                 1.9           Yes                   75.7          5.3
79994                 3.2            No                   96.0          6.8
79997                 1.6           Yes                   46.1          8.3
79998                 0.6           Yes                   58.7          5.8
79999                 4.5           Yes                   97.7          5.3

      diet_quality  ...  screen_time  study_environment access_to_tutoring  \
0             Poor  ...         10.9  Co-Learning Group                Yes
1             Good  ...          8.3  Co-Learning Group                Yes
3             Fair  ...         11.7  Co-Learning Group                Yes
4             Good  ...          9.4         Quiet Room                Yes
6             Good  ...          9.2               Dorm                Yes
...            ...  ...          ...                ...                ...
79993         Good  ...          6.1         Quiet Room                Yes
79994         Good  ...          9.7            Library                 No
79997         Good  ...          7.5               Dorm                 No
79998         Good  ...          9.3         Quiet Room                Yes
79999         Fair  ...         12.2  Co-Learning Group                Yes

       family_income_range parental_support_level  motivation_level  \
0                     High                      9                 7
1                      Low                      7                 2
3                      Low                      5                 3
4                   Medium                      9                 1
6                     High                      5                 7
...                    ...                    ...               ...
79993               Medium                      2                 3
79994                  Low                      2                 1
79997               Medium                      7                 1
79998                  Low                      2                 8
79999               Medium                      1                 8

       exam_anxiety_score  learning_style time_management_score  exam_score
0                       8         Reading                   3.0         100
1                      10         Reading                   6.0          99
3                      10         Reading                   3.2         100
4                      10         Reading                   7.1          98
6                       8     Kinesthetic                  10.0          97
...                   ...             ...                   ...         ...
79993                  10     Kinesthetic                   8.3          60
79994                  10        Auditory                   1.6         100
79997                  10          Visual                   1.3          89
79998                   7     Kinesthetic                   3.7          96
79999                   7         Reading                   6.7         100

[67643 rows x 30 columns]

In [18]:
sorted_age = df.sort_values(by='age')
print(sorted_age)

       student_id  age  gender             major  study_hours_per_day  \
75         100075   16    Male       Engineering             6.200000
38343      138343   16    Male  Computer Science             1.749082
79976      179976   16   Other       Engineering             1.700000
79912      179912   16  Female        Psychology             6.100000
79915      179915   16  Female              Arts             2.400000
...           ...  ...     ...               ...                  ...
79952      179952   28    Male        Psychology             8.000000
79958      179958   28    Male        Psychology             5.300000
79963      179963   28    Male       Engineering             4.400000
24550      124550   28   Other              Arts             4.600000
79993      179993   28    Male              Arts             1.300000

       social_media_hours part_time_job  attendance_percentage  sleep_hours  \
75                    4.4           Yes                   90.8          7.3
38343                 4.3            No                   87.8          7.5
79976                 3.1           Yes                   64.5          5.2
79912                 4.7           Yes                   67.4          6.3
79915                 3.6            No                   60.5          4.8
...                   ...           ...                    ...          ...
79952                 4.8           Yes                   90.3          7.4
79958                 2.7            No                   96.5          8.2
79963                 0.7            No                   89.7          4.0
24550                 2.1            No                   48.9          8.3
79993                 1.9           Yes                   75.7          5.3

      diet_quality  ...  screen_time  study_environment access_to_tutoring  \
75            Fair  ...         14.1               Cafe                 No
38343         Fair  ...          9.8            Library                 No
79976         Good  ...          6.2            Library                 No
79912         Good  ...         13.7               Cafe                Yes
79915         Fair  ...          9.2               Cafe                Yes
...            ...  ...          ...                ...                ...
79952         Good  ...         15.6  Co-Learning Group                 No
79958         Good  ...         10.6               Cafe                 No
79963         Good  ...          7.3               Cafe                 No
24550         Good  ...         11.5               Cafe                Yes
79993         Good  ...          6.1         Quiet Room                Yes

       family_income_range parental_support_level  motivation_level  \
75                    High                      6                 7
38343                 High                      6                 7
79976                  Low                      2                 9
79912                  Low                      7                 7
79915                  Low                      5                 6
...                    ...                    ...               ...
79952                 High                      8                 5
79958               Medium                      4                 3
79963               Medium                      8                 1
24550                  Low                      9                 9
79993               Medium                      2                 3

       exam_anxiety_score  learning_style time_management_score  exam_score
75                      8          Visual                   4.3          98
38343                   8          Visual                   1.6          71
79976                   6          Visual                   7.0          98
79912                   8          Visual                   2.8          88
79915                   9         Reading                   6.8         100
...                   ...             ...                   ...         ...
79952                  10          Visual                   4.3         100
79958                  10        Auditory                   6.9          95
79963                  10     Kinesthetic                   9.3          85
24550                   6        Auditory                   7.0          85
79993                  10     Kinesthetic                   8.3          60

[80000 rows x 30 columns]

In [19]:
grouped_df=df.groupby('age')['study_hours_per_day'].mean()
print(grouped_df)

age
16    4.209825
17    4.186619
18    4.163518
19    4.136791
20    4.174214
21    4.181451
22    4.180879
23    4.186182
24    4.154454
25    4.151867
26    4.187578
27    4.158254
28    4.195360
Name: study_hours_per_day, dtype: float64

In [20]:
df.rename(columns={'major':'major_subject'}, inplace=True)
print(df)

       student_id  age  gender     major_subject  study_hours_per_day  \
0          100000   26    Male  Computer Science             7.645367
1          100001   28    Male              Arts             5.700000
2          100002   17    Male              Arts             2.400000
3          100003   27   Other        Psychology             3.400000
4          100004   25  Female          Business             4.700000
...           ...  ...     ...               ...                  ...
79995      179995   16    Male       Engineering             3.700000
79996      179996   16  Female          Business             1.200000
79997      179997   26  Female              Arts             4.100000
79998      179998   23   Other           Biology             3.800000
79999      179999   25   Other       Engineering             3.000000

       social_media_hours part_time_job  attendance_percentage  sleep_hours  \
0                     3.0           Yes                   70.3          6.2
1                     0.5            No                   88.4          7.2
2                     4.2            No                   82.1          9.2
3                     4.6           Yes                   79.3          4.2
4                     0.8           Yes                   62.9          6.5
...                   ...           ...                    ...          ...
79995                 2.1           Yes                   80.8          6.1
79996                 0.4            No                   99.5          4.1
79997                 1.6           Yes                   46.1          8.3
79998                 0.6           Yes                   58.7          5.8
79999                 4.5           Yes                   97.7          5.3

      diet_quality  ...  screen_time  study_environment access_to_tutoring  \
0             Poor  ...         10.9  Co-Learning Group                Yes
1             Good  ...          8.3  Co-Learning Group                Yes
2             Good  ...          8.0            Library                Yes
3             Fair  ...         11.7  Co-Learning Group                Yes
4             Good  ...          9.4         Quiet Room                Yes
...            ...  ...          ...                ...                ...
79995         Fair  ...          8.3            Library                 No
79996         Good  ...          4.7  Co-Learning Group                 No
79997         Good  ...          7.5               Dorm                 No
79998         Good  ...          9.3         Quiet Room                Yes
79999         Fair  ...         12.2  Co-Learning Group                Yes

       family_income_range parental_support_level  motivation_level  \
0                     High                      9                 7
1                      Low                      7                 2
2                     High                      3                 9
3                      Low                      5                 3
4                   Medium                      9                 1
...                    ...                    ...               ...
79995                  Low                      1                 4
79996                  Low                      3                 2
79997               Medium                      7                 1
79998                  Low                      2                 8
79999               Medium                      1                 8

       exam_anxiety_score  learning_style time_management_score  exam_score
0                       8         Reading                   3.0         100
1                      10         Reading                   6.0          99
2                       6     Kinesthetic                   7.6          98
3                      10         Reading                   3.2         100
4                      10         Reading                   7.1          98
...                   ...             ...                   ...         ...
79995                  10        Auditory                   5.3          88
79996                  10     Kinesthetic                   6.8          52
79997                  10          Visual                   1.3          89
79998                   7     Kinesthetic                   3.7          96
79999                   7         Reading                   6.7         100

[80000 rows x 30 columns]

In [21]:
df['exam_result']=df['exam_score'].apply(lambda x:'PASS' if x>=45 else'FAIL')
print(df)

       student_id  age  gender     major_subject  study_hours_per_day  \
0          100000   26    Male  Computer Science             7.645367
1          100001   28    Male              Arts             5.700000
2          100002   17    Male              Arts             2.400000
3          100003   27   Other        Psychology             3.400000
4          100004   25  Female          Business             4.700000
...           ...  ...     ...               ...                  ...
79995      179995   16    Male       Engineering             3.700000
79996      179996   16  Female          Business             1.200000
79997      179997   26  Female              Arts             4.100000
79998      179998   23   Other           Biology             3.800000
79999      179999   25   Other       Engineering             3.000000

       social_media_hours part_time_job  attendance_percentage  sleep_hours  \
0                     3.0           Yes                   70.3          6.2
1                     0.5            No                   88.4          7.2
2                     4.2            No                   82.1          9.2
3                     4.6           Yes                   79.3          4.2
4                     0.8           Yes                   62.9          6.5
...                   ...           ...                    ...          ...
79995                 2.1           Yes                   80.8          6.1
79996                 0.4            No                   99.5          4.1
79997                 1.6           Yes                   46.1          8.3
79998                 0.6           Yes                   58.7          5.8
79999                 4.5           Yes                   97.7          5.3

      diet_quality  ...  study_environment access_to_tutoring  \
0             Poor  ...  Co-Learning Group                Yes
1             Good  ...  Co-Learning Group                Yes
2             Good  ...            Library                Yes
3             Fair  ...  Co-Learning Group                Yes
4             Good  ...         Quiet Room                Yes
...            ...  ...                ...                ...
79995         Fair  ...            Library                 No
79996         Good  ...  Co-Learning Group                 No
79997         Good  ...               Dorm                 No
79998         Good  ...         Quiet Room                Yes
79999         Fair  ...  Co-Learning Group                Yes

      family_income_range  parental_support_level motivation_level  \
0                    High                       9                7
1                     Low                       7                2
2                    High                       3                9
3                     Low                       5                3
4                  Medium                       9                1
...                   ...                     ...              ...
79995                 Low                       1                4
79996                 Low                       3                2
79997              Medium                       7                1
79998                 Low                       2                8
79999              Medium                       1                8

       exam_anxiety_score  learning_style  time_management_score exam_score  \
0                       8         Reading                    3.0        100
1                      10         Reading                    6.0         99
2                       6     Kinesthetic                    7.6         98
3                      10         Reading                    3.2        100
4                      10         Reading                    7.1         98
...                   ...             ...                    ...        ...
79995                  10        Auditory                    5.3         88
79996                  10     Kinesthetic                    6.8         52
79997                  10          Visual                    1.3         89
79998                   7     Kinesthetic                    3.7         96
79999                   7         Reading                    6.7        100

       exam_result
0             PASS
1             PASS
2             PASS
3             PASS
4             PASS
...            ...
79995         PASS
79996         PASS
79997         PASS
79998         PASS
79999         PASS

[80000 rows x 31 columns]

In [23]:
#Insted of lambda
def categorize_age(Years):
    if Years<18:
        return 'child'
    else:
        return 'Adult'

df['Age_category'] = df['age'].apply(categorize_age)
print(df)

       student_id  age  gender     major_subject  study_hours_per_day  \
0          100000   26    Male  Computer Science             7.645367
1          100001   28    Male              Arts             5.700000
2          100002   17    Male              Arts             2.400000
3          100003   27   Other        Psychology             3.400000
4          100004   25  Female          Business             4.700000
...           ...  ...     ...               ...                  ...
79995      179995   16    Male       Engineering             3.700000
79996      179996   16  Female          Business             1.200000
79997      179997   26  Female              Arts             4.100000
79998      179998   23   Other           Biology             3.800000
79999      179999   25   Other       Engineering             3.000000

       social_media_hours part_time_job  attendance_percentage  sleep_hours  \
0                     3.0           Yes                   70.3          6.2
1                     0.5            No                   88.4          7.2
2                     4.2            No                   82.1          9.2
3                     4.6           Yes                   79.3          4.2
4                     0.8           Yes                   62.9          6.5
...                   ...           ...                    ...          ...
79995                 2.1           Yes                   80.8          6.1
79996                 0.4            No                   99.5          4.1
79997                 1.6           Yes                   46.1          8.3
79998                 0.6           Yes                   58.7          5.8
79999                 4.5           Yes                   97.7          5.3

      diet_quality  ...  access_to_tutoring family_income_range  \
0             Poor  ...                 Yes                High
1             Good  ...                 Yes                 Low
2             Good  ...                 Yes                High
3             Fair  ...                 Yes                 Low
4             Good  ...                 Yes              Medium
...            ...  ...                 ...                 ...
79995         Fair  ...                  No                 Low
79996         Good  ...                  No                 Low
79997         Good  ...                  No              Medium
79998         Good  ...                 Yes                 Low
79999         Fair  ...                 Yes              Medium

      parental_support_level  motivation_level exam_anxiety_score  \
0                          9                 7                  8
1                          7                 2                 10
2                          3                 9                  6
3                          5                 3                 10
4                          9                 1                 10
...                      ...               ...                ...
79995                      1                 4                 10
79996                      3                 2                 10
79997                      7                 1                 10
79998                      2                 8                  7
79999                      1                 8                  7

       learning_style  time_management_score  exam_score exam_result  \
0             Reading                    3.0         100        PASS
1             Reading                    6.0          99        PASS
2         Kinesthetic                    7.6          98        PASS
3             Reading                    3.2         100        PASS
4             Reading                    7.1          98        PASS
...               ...                    ...         ...         ...
79995        Auditory                    5.3          88        PASS
79996     Kinesthetic                    6.8          52        PASS
79997          Visual                    1.3          89        PASS
79998     Kinesthetic                    3.7          96        PASS
79999         Reading                    6.7         100        PASS

       Age_category
0             Adult
1             Adult
2             child
3             Adult
4             Adult
...             ...
79995         child
79996         child
79997         Adult
79998         Adult
79999         Adult

[80000 rows x 32 columns]